### ISSUE TITLE
'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by zenhunt** [python-pinot-dbapi/pinot-dbapi#26]
A simple test with version 0.3.10 on superset or even a simple demo script against my cluster currently results in the following error:

Traceback (most recent call last):
  File "/home/marko/projects/ASW/files/pinot-dbapi/examples/pinot-live.py", line 6, in <module>
    engine = create_engine(
  File "<string>", line 2, in create_engine
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 576, in create_engine
    (cargs, cparams) = dialect.create_connect_args(u)
  File "/home/marko/.local/lib/python3.10/site-packages/pinotdb/sqlalchemy.py", line 203, in create_connect_args
    kwargs = self.update_from_kwargs(kwargs)
  File "/home/marko/.local/lib/python3.10/site-packages/pinotdb/sqlalchemy.py", line 172, in update_from_kwargs
    kwargs["verify_ssl"] = self._verify_ssl = (kwargs.get("verify_ssl", "true").lower() in ['true'])
AttributeError: 'bool' object has no attribute 'lower'

I'm using a simple pinot cluster based on docker swarm, the code that produces this error is the following:

# Query pinot.live with sqlalchemy
from sqlalchemy import *
from sqlalchemy.engine import create_engine
from sqlalchemy.schema import *

engine = create_engine(
    "pinot+http://pinot-broker.studiobot:8099/query/sql?controller=http://pinot-controller.studiobot:9020/"
)

meetupRsvp = Table("meetupRsvp_REALTIME", MetaData(bind=engine), autoload=True)
print(f"\nSending Count(*) SQL to Pinot")
query=select([func.count("*")], from_obj=meetupRsvp)
print(engine.execute(query).scalar())

Please fix.

**Comment by xiangfu0** [comment]
Thanks for reporting! Will take a look and fix soon.

**Comment by xiangfu0** [comment]
Just published 0.3.11, can u help test it?

**Comment by zenhunt** [comment]
Just did, Looks good so far. I'll keep you posted.

#closed
