### ISSUE TITLE
Split extra header on first "="

### ISSUE THREAD

**Issue by yomikaze** [python-pinot-dbapi/pinot-dbapi#83]
The extra header key value pairs should be split on the first "=" to allow for values containing "=" characters.

[This code on line 333](https://github.com/python-pinot-dbapi/pinot-dbapi/blob/master/pinotdb/db.py#L333):
```
k, v = header.split("=")
```
should be:
```
k, v = header.split("=", 1)
```

Otherwise there is an error:
```
>>> curs = conn.cursor()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/pinotdb/db.py", line 57, in g
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pinotdb/db.py", line 185, in cursor
    cursor = Cursor(*self._args, **self._kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pinotdb/db.py", line 333, in __init__
    k, v = header.split("=")
    ^^^^
ValueError: too many values to unpack (expected 2)
```

**Comment by xiangfu0** [comment]
Close this since it's fixed in #84
